require 'twitter'

class DataSource
  include Mongoid::Document

  # Attribute listing
  field :user_id, type: String
  field :last_crawl, type: DateTime
  
  # Validations
  validates :user_id, presence: true
  
  # Relations
  belongs_to :unknown_subject
  has_many :status_updates

  def fetch_status_updates
    twitter = Twitter.new(unknown_subject.user.access_token)
    twitter.tweets(self.user_id) do |tweet|
      unless status_updates.find_by(id_str: tweet['id_str'])
        $stderr.puts(tweet.inspect)
      
        # HACK: We skip the ID attribute because those should be autogenerated
        # by Mongoid/MongoDB, otherwise relations do not work properly
        status_update = status_updates.new
        tweet.each { |k,v| status_update[k] = v unless k.match(/^id$/) }
        status_update.save
      end
    end
  end
end
